//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BillingModelContainer : DbContext
    {
        public BillingModelContainer()
            : base("name=BillingModelContainer")
        {
    		this.Database.Log = x=>Console.WriteLine(x);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> ClientSet { get; set; }
        public DbSet<Contract> ContractSet { get; set; }
        public DbSet<CallInfo> CallInfoSet { get; set; }
        public DbSet<BillingPlan> BillingPlanSet { get; set; }
        public DbSet<ContractBillingPlanBinding> ContractBillingPlanBindingSet { get; set; }
        public DbSet<Terminal> TerminalSet { get; set; }
    }
}
