//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractBillingPlanBinding
    {
        public System.Guid Id { get; set; }
        public System.DateTime BindingDate { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual BillingPlan BillingPlan { get; set; }
    }
}
